name: Hello from another private action
on: push
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout WtfJoke/hello-world-docker-action
        uses: actions/checkout@v2
        with:
          repository: WtfJoke/hello-world-docker-action
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false
          ref: refs/heads/main
          # path: ./.github/actions/hello
      - run: ls -la ./.github/
      - run: echo "SECRET=HI" >> $GITHUB_ENV
      - uses: ./.github/actions/hello
        with:
          who-to-greet: "Mona the Octocat - $SECRET"
      - name: Last step
        run: echo "hi"
